### ISSUE TITLE
On esp8266 

### ISSUE THREAD

**Issue by Gorgon-hail** [HackerNowful/key-fob-Jammer#1]
Can we do the same with esp8266?

**Comment by HackerNowful** [comment]
yes You Can do , The d1 mini is an ESP8266. you can use this code to node mcu and all kind of esp8266

**Comment by Gorgon-hail** [comment]
What about the connections ? . Like you showed in the diagram. Will they be same ?

**Comment by HackerNowful** [comment]
yes
